name: Build

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/build.yml
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/build.yml

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v4.0.0-rc3

    - name: Configure CMake (Linux and macOS)
      if: runner.os != 'Windows'
      run: mkdir build; cd build; cmake -G Ninja -S ../src

    - name: Set up MSBuild
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Find Visual Studio installation path
      if: runner.os == 'Windows'
      run: |
        $vsInstallPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
        echo "##[set-output name=vsInstallPath;$vsInstallPath]"

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      run: |
        mkdir build
        cd build
        ${{ steps.vsInstallPath.outputs.vsInstallPath }}\VC\Auxiliary\Build\vcvarsall.bat x64
        cmake -G "Ninja" -S ../src

    - name: Build
      run: cd build; ninja
