name: Build

on:
  push:
    branches:
      - main
    paths:
      - src/**
  pull_request:
    branches:
      - main
    paths:
      - src/**

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v4.0.0-rc3

    - name: Configure CMake (Linux and macOS)
      if: runner.os != 'Windows'
      run: mkdir build; cd build; cmake -G Ninja -S ../src

    - name: Set up MSBuild
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      run: |
        mkdir build
        cd build
        cmake -G "Ninja" -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe -S ../src

    - name: Build
      run: cd build; ninja
