name: Run

on:
  workflow_dispatch:
    inputs:
      run_description:
        description: 'description'
        required: false
        default: nightly
  push:
    branches:
      - run
    paths:
      - trigger/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: run

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Install Cloudflared
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/download/2025.2.1/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb
        sudo sysctl -w net.core.rmem_max=7500000
        sudo sysctl -w net.core.wmem_max=7500000
    - name: Install Wireguard
      run: |
        sudo apt-get install -y wireguard
    - name: Configure Wireguard
      run: |
        echo "${{ secrets.WIREGUARD_CONFIG }}" | sudo tee /etc/wireguard/wg0.conf
      shell: bash
    - name: Start Wireguard
      run: |
          # sudo sysctl -w net.ipv4.ip_forward=1
          sudo wg-quick up wg0
          ifconfig
          sysctl net.ipv4.ip_forward
          sudo iptables -t nat -L

    - name: Configure DNS
      run: |
        sudo echo "DNSStubListener=yes" >> /etc/systemd/resolved.conf
        sudo echo "DNSStubListenerExtra=0.0.0.0" >> /etc/systemd/resolved.conf

    - name: Install Server
      run: |
       wget https://github.com/xiguichen/tcpudp/releases/download/v0.3.7/tcpudp-ubuntu-latest.tar.gz
       ls
       tar xvf tcpudp-ubuntu-latest.tar.gz
       chmod +x tcpudp-ubuntu-latest/server
    - name: Run Cloudflared
      run: |
        sudo cloudflared tunnel --url tcp://localhost:7001 --logfile cloudflare.log &
        until grep -q "https.*trycloudflare.com" cloudflare.log; do sleep 1; done
        echo -n "cloudflared access tcp --url tcp://localhost:7001 --hostname " > ${{ github.workspace }}/cloudflare.sh
        cat cloudflare.log | grep https.*trycloudflare.com -o >> ${{ github.workspace }}/cloudflare.sh
        cp ${{ github.workspace }}/cloudflare.sh ${{ github.workspace }}/cloudflare.bat
        chmod +x ${{ github.workspace }}/cloudflare.sh
    - name: Commit Change
      working-directory: ${{ github.workspace }}
      run: |
          git add cloudflare.sh cloudflare.bat
          git commit -m "Auto-update"
          git push origin run
     

    - name: Run Server
      run: |
        tcpudp-ubuntu-latest/server
