on:
  push:
    branches:
      - run
  pull_request:
    branches:
      - run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Cloudflared
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/download/2025.2.1/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb

    - name: Install Wireguard
      run: |
        sudo apt-get install -y wireguard

    - name: Run Cloudflared
      run: |
        cloudflared --version

    - name: Install Server
      run: |
       wget https://github.com/xiguichen/tcpudp/actions/runs/13926317257/artifacts/2773375858
       ls
       
