name: Run

on:
  workflow_dispatch:
    inputs:
      run_description:
        description: 'description'
        required: false
        default: nightly
  push:
    branches:
      - run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Cloudflared
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/download/2025.2.1/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb

    - name: Install Wireguard
      run: |
        sudo apt-get install -y wireguard
    - name: Configure Wireguard
      run: |
        echo "${{ secrets.WIREGUARD_CONFIG }}" | sudo tee /etc/wireguard/wg0.conf
      shell: bash
    - name: Start Wireguard
      run: |
          # sudo sysctl -w net.ipv4.ip_forward=1
          sudo wg-quick up wg0
          ifconfig
          sysctl net.ipv4.ip_forward
          sudo iptables -t nat -L

    - name: Install Server
      run: |
       wget https://github.com/xiguichen/tcpudp/releases/download/nightly/tcpudp-ubuntu-latest.tar.gz
       ls
       tar xvf tcpudp-ubuntu-latest.tar.gz
       chmod +x tcpudp-ubuntu-latest/server
    - name: Run Server
      run: |
        nohup tcpudp-ubuntu-latest/server &
    - name: Run Cloudflared
      run: |
        cloudflared tunnel --url tcp://localhost:6001
